name: CI/CD

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  pull-request:
    name: Pull request
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
